export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  COLOR :'COLOR',
  SET_COLOR :'SET_COLOR',
  STORAGE : 'STORAGE',
  CART_SELECTED_PRODUCT: "CART_SELECTED_PRODUCT",
  // IS_ACTIVE : 'IS_ACTIVE',
};